### PR TITLE
Install manually on Linux

### PR DESCRIPTION
**Pull request by basxto**
This will be only useful in releases

### CODE REVIEW

**Comment by MikeMaximus** [comment]
Great idea!

I tested it but it's failing for me, I'm unsure why.  I'm not well versed with makefile syntax or the xdg utilties.

```
mike@ubuntu-vbox:~/Host/gbm$sudo make install
#This needs xdg-utils
chmod +x GBM.exe
cp GBM.exe /usr/local/bin/gbm
for i in {16,24,32,48,64,72,96,128,256};do xdg-icon-resource install --mode system --novendor --noupdate --size ${i} gbm_${i}x${i}.png gbm; done
xdg-icon-resource: size argument must be numeric
Try 'xdg-icon-resource --help' for more information.
makefile:2: recipe for target 'install' failed
make: *** [install] Error 1
```

**Comment by basxto** [comment]
Can you replace it by `for i in {16,24,32,48,64,72,96,128,256};do echo xdg-icon-resource install --mode system --novendor --noupdate --size ${i} gbm_${i}x${i}.png gbm; done`?

I suspect, it does not replace the variable like I expected it.

**Comment by MikeMaximus** [comment]
That works now.

However the desktop file tries to launch the exe with Wine, which is probably the default configuration in Ubuntu.  If I change it to the following then it works.

```
Path=/usr/local/bin
TryExec=mono
Exec=mono gbm
Terminal=false
```

**Comment by basxto** [comment]
The code I wrote, outputs the command instead of executing it.
I don’t have wine installed, I will change it to `mono gbm`.
Even though I do not understand why it’s working, since in a terminal that won’t work.

**Comment by MikeMaximus** [comment]
Right, didn't notice the echo when I pasted.  The fact it finished and created the png's led me to believe it worked.

It doesn't replace the variable as you said.

**Pull request closed without merging**
