### PR TITLE
Start GBM via script

### LINKED ISSUE #110: Add shell script for starting on Linux
Not any machine is able to run `GBM.exe` directly, therefor an executable script is necessary for that.

That script  should report when it can’t find `GBM.exe` and also check for the existence of all external programs, GBM depends on.

(For me, but I can’t assign)

### PR DESCRIPTION
**Pull request by basxto**
Add a script that can launch GBM from several locations

Fix #110 

Forgot to push

### CODE REVIEW

**Comment by MikeMaximus** [comment]
I was testing on Ubuntu 16.04, there's no error message but the script says I have none of the dependencies installed and exits.

**Comment by basxto** [comment]
I will check that during my break at work (use 16.04 there)

**Comment by basxto** [comment]
The check for libsqlite3 did not work on ubuntu, but I’m about to fix that.
The installation does not check for and install the dependencies, that’s what package managers are for.

I know how to build packages for Debian/Ubuntu (`.deb`) and for Archlinux (`.pkg.tar.xz`), I dunno if it would be helpful to put those into the release.

I will definitely add a package to the Archlinux User Repository from the next release on, the `PKGBUILD`-script for that is already done. That’s also why I wanted release version and filename to match.

And other than Archlinux do Debian/Ubuntu have multiple versions, so it’s possible that one would need to build several packages. But maybe we are lucky and it’d work with all.

I can look into that if you want, maybe I find a way to build that from Windows with mingw or so.
[Wpkg](https://en.wikipedia.org/wiki/Wpkg) seems to be a native port.
But you still need to run my `makefile`, which needs `make`, `install`, `xdg-icon-resource`, `xdg-desktop-menu`, `rm` and `imagemagick`.

I do not use the makefile for my `PKGBUILD` yet, but maybe would be wise adapt the `makefile` so that it can be used for such things.

**Comment by basxto** [comment]
Sorry, I wasn’t aware, that pull requests are dynamic

**Comment by basxto** [comment]
For my `PKGBUILD` I’ll run it as `make -C ${srcdir} install DESTDIR="${pkgdir}/" PREFIX=/usr`, should be similar for Debian/Ubuntu

**Comment by MikeMaximus** [comment]
Thanks for your work on this basxto.  I still have a few issues.

1.  Should the prefix in the makefile just be `usr/local` instead of `/usr/local` . It doesn't seem to matter either way but the double // looked weird.
2.  I'm still having issues with the detection of dependencies (but libsqlite3 works).  I did a bit of reading because I'm not familiar with shell script syntax.  When I change the loop to the following, then it works as expected.
```
for prog in mono readlink df 7za;do 
```
I also get some other errors in the script.
```
/usr/local/bin/gbm: 9: /usr/local/bin/gbm: Bad substitution
Located in /home/mike
/usr/local/bin/gbm: 13: [: closing paren expected
/usr/local/bin/gbm: 15: [: closing paren expected
```
I'm not really sure what's going on with line 9, so maybe you can take a look.

**Comment by basxto** [comment]
Will check it at work.
I just copied it to my shell, but I use zsh both at work and here.
It seems, I used bash syntax and ubuntu uses a different shell for running scripts.

`{mono,readlink,df,7za}` results in `mono readlink df 7za`, it’s a bit overkill in that situation, but I like it’s readability.

The rest are parsing errors.
`[` is program/command for comparations, but  
```
[ -n "`whereis -b ${prog} | cut -sd' ' -f2`" ]
```
resulted in more than one command, they are actually 3, but 2 are nested.

**Comment by basxto** [comment]
Can reproduce:

```
$ dash ./gbm.sh
Please install {mono,readlink,df,7za}
./gbm.sh: 9: ./gbm.sh: Bad substitution
Located in /home/dabascht/projects/gbm
./gbm.sh: 13: [: closing paren expected
./gbm.sh: 15: [: closing paren expected
GBM.exe not found
```

**Comment by MikeMaximus** [comment]
Thanks! Just one more thing I had an issue with.

I get this error if the script runs from anywhere but root.

`/usr/local/bin/gbm: 9: cd: can't cd to /home/mike//usr/local/bin`

Line 9: `DIR="$( cd "$( dirname "$(pwd)/$0" )" && pwd )";`

Do we need $(pwd)/ in there?

**Comment by basxto** [comment]
I run into that problem myself, I fixed it.

**Pull request merged**
